### PR TITLE
Fix serverless-offline hook

### PR DESCRIPTION
**Pull request by jay-snyder**
## Issue

#46

## What

The baker was being ran when using the command `serverless offline start` but not `serverless offline`. Fixed the hook so both commands trigger the baker.

## Test

* `serverless offline start` and confirm Serverless Secrets begins packaging process
* `serverless offline` and confirm Serverless Secrets begins packaging process

## Checks

- [x] Has the version number been incremented in package.json and package-lock.json

### CODE REVIEW

**Comment by cruisercohen** [comment]
Looks great!

**Review by cruisercohen — DISMISSED** [review]

**Comment by jay-snyder** [comment]
Looks like the build CI step is failing, not sure why at this moment. Any insight?

**Comment by cruisercohen** [comment]
The full output is viewable in the `Details` link of the failing step

**Comment by cruisercohen** [comment]
the env variable does seem to exist in the circle ci config for this project, not sure why that didn't work, maybe a retry as the this step worked just a couple days ago?

**Review by piohhmy — APPROVED** [review]
Looks great!  Thanks for contributing! 💯

**Pull request merged**
